### ISSUE TITLE
Setup DB & Object Storage

### ISSUE THREAD

**Issue by ekinbukulmez** [ekinbukulmez/CITS3200-Project#18]
Set up MongoDB and cloud storage for storing information on images.

Tasks
- [x] Set up MongoDB,
- [x] Set up Google Cloud storage.
- [x] Achieve peak storage.
- [x] Tests 
- [ ] Documentation

**Comment by Naazyon** [comment]
No tests for setup. Documentation will be added on google drive/documentation/issue18
