### ISSUE TITLE
Report on progress

### ISSUE THREAD

**Issue by ekinbukulmez** [ekinbukulmez/CITS3200-Project#21]
**Description**
Make backend endpoint that reports on the progress of image processing.

**Definition of done**
- Functional endpoint
- Given id of a task
- Return the progress of the task
    - % of processed/unprocessed task
    - number of animal images
    - number of blank images

**Tasks**
- [x] Establish endpoint.
- [x] Determine progress status.
- [x] Send progress status to frontend.
- [ ] Tests
- [ ] Documentation

**Comment by Pixeladed** [comment]
@systemvaz, could you briefly explain the expected request format and expected response content? Just need this information so I know what to expect when building the frontend

**Comment by systemvaz** [comment]
@Pixeladed as discussed, request to be made via:  /progress/:id
Where id is the project id. Response will be json with array of image urls in following format:
{
    pending: ['image 1'],
    animal: ['image 2'],
    blank: ['image 3]
}
